apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aspnetapi-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # Make sure to include Strict-Transport-Security response header by Ingress.
    nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "Strict-Transport-Security: max-age=31536000; includeSubDomains; preload";
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aspnetapi
            port:
              number: 80
  - host: aspnetapi.internal
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aspnetapi
            port:
              number: 80