# global values
global:
  env: 
    "ASPNETCORE_ENVIRONMENT": "Staging"
    "ASPNETCORE_FORWARDEDHEADERS_ENABLED": "true"

aspnetapi:

  replicaCount: 1

  env: 
    "ASPNETCORE_ENVIRONMENT": "Staging"
    "ASPNETCORE_FORWARDEDHEADERS_ENABLED": "true"

  image:
    repository: aspnetapi
    pullPolicy: IfNotPresent
    tag: ""

  service:
    type: NodePort
    port: 80

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "Request-Id: $req_id";
    hosts:
      - host: "aspnetapi"
        paths: 
            - path: /
              pathType: ImplementationSpecific

  autoscaling:
    enabled: false

  serviceAccount:
    create: false