aspnetapi:

  replicaCount: 1

  env:
    "ASPNETCORE_ENVIRONMENT": "Staging"
    # This will enable ForwarHeaders middleware, so the application knows it’s behind a reverse-proxy (in this case an NGINX ingress controller).
    "ASPNETCORE_FORWARDEDHEADERS_ENABLED": "true"

  image:
    repository: aspnetapi
    pullPolicy: IfNotPresent
    tag: ""

  service:
    type: NodePort
    port: 80

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      # Make sure to include Strict-Transport-Security response header by Ingress.
      nginx.ingress.kubernetes.io/configuration-snippet: |
          more_set_headers "Strict-Transport-Security: max-age=31536000; includeSubDomains; preload";
    hosts:
      - host: "aspnetapi.internal"
        paths: 
            - path: /
              pathType: ImplementationSpecific

  autoscaling:
    enabled: false

  serviceAccount:
    create: false