name: Docker Image CI

on:
  workflow_dispatch:

  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASSWORD }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ivanenkomak/aspnetapi

      - name: Build and push
        run: |
          IMAGE_TAG="ivanenkomak/aspnetapi:latest"
          DOCKERFILE="AspNetApi/Dockerfile"
          echo "Building Docker image with latest tag: ${IMAGE_TAG}"
          docker buildx build -t "${IMAGE_TAG}" --file "${DOCKERFILE}" . --push